services:
  amaru:
    build:
      context: .
      dockerfile: Dockerfile.amaru
    container_name: amaru
    working_dir: /srv/amaru
    depends_on:
      cardano:
        condition: service_healthy
    command:
      [
        "bootstrap",
        "--peer-address", "cardano:3001",
        "--config-dir", "${CONFIG_FOLDER:-/opt/amaru/config}",
        "--ledger-dir", "${LEDGER_DIR:-ledger.db}",
        "--chain-dir", "${CHAIN_DIR:-chain.db}",
        "--network", "${NETWORK?Define NETWORK in .env with a value supported by Amaru}",
      ]
    volumes:
      - amaru_data:/srv/amaru

  cardano:
    image: ghcr.io/blinklabs-io/cardano-node
    container_name: cardano
    environment:
      - NETWORK
    volumes:
      - cardano_data:/data/db
    healthcheck:
      test: ["CMD", "bash", "-c", "echo testing > /dev/tcp/localhost/3001"]
      interval: 1m30s
      timeout: 10s
      retries: 100
      start_period: 40s
      start_interval: 5s

  debug:
    image: debian:latest
    container_name: debian-container
    command: tail -f /dev/null # Waits forever for someone to exec into it
    profiles:
      - debug

volumes:
  amaru_data:
  cardano_data: