name: Docker Compose CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create cache folders
        run: |
          mkdir -p ./_cache/amaru_data
          mkdir -p ./_cache/cardano_data

      - name: Restore Cardano data from cache
        uses: actions/cache@v4
        with:
          path: ./_cache/cardano_data
          key: cardano_data-mainnet-${{ github.run_id }}
          restore-keys: |
            cardano_data-mainnet

      - name: Start Cardano and Amaru cluster
        env:
          NETWORK: mainnet
        run: |
          docker compose version
          docker compose -f docker-compose.yml -f .github/utils/docker-compose.override.yml pull
          docker compose -f docker-compose.yml -f .github/utils/docker-compose.override.yml build
          docker compose -f docker-compose.yml -f .github/utils/docker-compose.override.yml up -d cardano
          docker compose -f docker-compose.yml -f .github/utils/docker-compose.override.yml logs -f \
          | tee /dev/stderr \
          | (
              grep --line-buffered -m1 "at slot 162304620"
              docker compose -f docker-compose.yml -f .github/utils/docker-compose.override.yml down
            )

      - name: Prune Cardano data
        env:
          NETWORK: mainnet
        shell: bash
        working-directory: ./_cache/cardano_data
        run: |
          if [ "$NETWORK" == "preprod" ]; then
            rm -f immutable/00*.chunk immutable/01*.chunk immutable/02*.chunk immutable/030*.chunk
          fi

          if [ "$NETWORK" == "preview" ]; then
            rm -f immutable/0*.chunk immutable/10*.chunk immutable/11*.chunk
          fi

      - name: What are we about to save ?
        shell: bash
        run: |
          du -h ./_cache/

      - name: Upload Cardano data
        uses: actions/upload-artifact@v4
        with:
          name: cardano_data
          path: ./_cache/cardano_data
